---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by miao.
--- DateTime: 8/18/22 10:38 PM
---

LevelType = {
    Init = 0,
    Login = 1,
    Loader = 2,
    Main = 3,
    Battle = 4,
}