---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by miao.
--- DateTime: 8/18/22 11:58 PM
---


---@class SkillBase
local SkillBase = class("SkillBase")

function SkillBase:initialize()
    self.turn = 0  //  生效时机
    self.effect = 0 // 效果
    self.target = 0 //目标
    self.range = 0 //范围
end

return SkillBase