---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by miao.
--- DateTime: 8/18/22 11:56 PM
---

---@class EntityBase

local EntityBase = class("EntityBase")


function EntityBase:initialize()
    self.id = 0
end

return EntityBase