---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by miaowenjie.
--- DateTime: 8/22/22 10:32 PM
---



---@class BattleTeam
local BattleTeam = class("BattleTeam")


function BattleTeam:initialize(teamInfo)
    self.teamHp = teamInfo.hp
    self.teamId = teamInfo.id
    self.energy = 5
    self.energyMax = 10
    self.speed = 1000
    self.teamInfo = teamInfo
    ---@type BattleEntity[]
    self.battleEntities = {}
end

--function BattleTeam:Create()
--
--end

function BattleTeam:Destroy()
    self.battleEntities = nil
end

function BattleTeam:LateUpdate(deltaTime)
    self.energy = self.energy + self.speed * deltaTime
    if self.energy > self.energyMax  then
        self.energy = self.energyMax
    end
end

function BattleTeam:AddEntity(entity)
    self.battleEntities[entity.id] = entity
end

function BattleTeam:RemoveEntity(entity)
    self.battleEntities[entity.id] = nil
end

return BattleTeam