---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by miaowenjie.
--- DateTime: 8/23/22 12:03 AM
---


BattleMessageId = {
    Add2Pool = 1,
    Add2Field = 2,
    DoAction = 3,
    UseCard = 4,
}

BattleAtbMax = 5000
BattlePrepareMax = 3000