---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by miaowenjie.
--- DateTime: 8/22/22 9:37 PM
---

require("Battle.BattleConst")
---@class BattleMain
local BattleMain = class("BattleMain")


function BattleMain:initialize()
    ---@type BattleRoom[]
    self.battleRooms = nil

    ---@type BehaviorManager
    local mgr = MgrCenter:GetManager("Behavior")
    mgr:Register(self)

    ---@type MessageManager
    MessageMgr = require("Battle.Manager.MessageManager"):new()

end

function BattleMain:Update(deltaTime)
    self:UnpackMessage()
    for _, room in pairs(self.battleRooms) do
        room:Update(deltaTime)
    end

end

function BattleMain:UnpackMessage()
    local count = MessageMgr:Count()

    for i = 1, count do
        local msg = MessageMgr:Pop()
        self:ParseMessage(msg)
    end
end

function BattleMain:ParseMessage(message)
    if  self.battleRooms[message.roomId] then
        self.battleRooms[message.roomId]:ParseMessage(message)
    end
end

function BattleMain:LateUpdate(deltaTime)
    for _, room in pairs(self.battleRooms) do
        room:LateUpdate(deltaTime)
    end
end

function BattleMain:StartBattle(roomId,teamsInfo)
    log("[Battle] StartBattle " .. roomId)
    log("[Battle] teamInfo " ,teamsInfo)
    if self.battleRooms[roomId] == nil then
        local room = require("Battle.BattleRoom"):new(roomId)
        room:Create(teamsInfo)
        self.battleRooms[roomId] = room
    end
end

function BattleMain:StopBattle()

end

function BattleMain:Create()
    self.battleRooms = {}
end

function BattleMain:OnDestroy()
    ---@type BehaviorManager
    local mgr = MgrCenter:GetManager("Behavior")
    mgr:UnRegister(self)

    for _, room in pairs( self.battleRooms) do
        room:Destroy()
    end
end


---test
function BattleMain:TestBattle()
    self:StartBattle(1 , {
        {
            hp = 10,
            teamId = 1,
        },
        {
            hp = 11,
            teamId = 2,
        }
    })
    startTimer(1, 1, self, function()
        MessageMgr:Push(
        {
                cmd = BattleMessageId.UseCard,
                roomId = 1,
                cardId = 1,
                teamId = 1,
                pos = {1,1},
                targetId = nil,
            }
        )
    end)
end
return BattleMain