---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by miaowenjie.
--- DateTime: 8/23/22 12:31 AM
---

---@class BattleField
local BattleField = class("BattleField")


function BattleField:initialize(teamInfo)

    ---@type BattleEntity[]
    self.battleEntities = nil
    ---@type BattleTeam[]
    self.teams = nil

    self.grids = nil
    self:Create(teamInfo)
end

function BattleField:Create(teamsInfo)
    log("[Field] create! " ,teamsInfo)
    self.grids = {}
    for i = 1, 18 do
        self.grids[i] = nil
    end
    self.battleEntities = {}
    self.teams = {
        require("Battle.BattleTeam"):new(teamsInfo[1]),
        require("Battle.BattleTeam"):new(teamsInfo[2])
    }
end

function BattleField:Destroy()
    for _, team in pairs( self.teams) do
        team:Destroy()
    end

    for _, entity in pairs( self.battleEntities) do
        entity:Destroy()
    end

end

function BattleField:AddEntity(entity)
    local teamId = entity.teamId
    entity:EnterField()
    if self.teams[teamId] then
        self.teams[teamId]:AddEntity(entity)
    end
end

function BattleField:RemoveEntity(entity)
    local teamId = entity.teamId
    if self.teams[teamId] then
        self.teams[teamId]:RemoveEntity(entity)
    end
end


function BattleField:Update(deltaTime)
    for _, entity in pairs( self.battleEntities) do
        entity:Update(deltaTime)
    end
end
function BattleField:LateUpdate(deltaTime)
    for _, entity in pairs( self.battleEntities) do
        entity:LateUpdate(deltaTime)
    end

    for _, team in pairs( self.teams) do
        team:LateUpdate(deltaTime)
    end
end



return BattleField