---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by miao.
--- DateTime: 8/24/22 7:39 PM
---

local BattleHeroStone = class("BattleHeroStone")


function BattleHeroStone:initialize()

end

return BattleHeroStone

