---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by miaowenjie.
--- DateTime: 8/22/22 9:18 PM
---
local BuffBase = require "Battle.Buff.BuffBase"
--潜行
---@class AssaultBuff : BuffBase
local AssaultBuff = class("SneakBuff", BuffBase)

function AssaultBuff:initialize(...)

end

return AssaultBuff