---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by miao.
--- DateTime: 8/19/22 12:07 AM
---

local BuffBase = require "Battle.Buff.BuffBase"
--潜行
---@class SneakBuff : BuffBase
local SneakBuff = class("SneakBuff", BuffBase)

function SneakBuff:Ctor()
    self.id = 2
end

return SneakBuff