---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by miaowenjie.
--- DateTime: 8/22/22 9:17 PM
---

local AttBase = require "Battle.Buff.AttBase"
-- 属性
---@class SpeedAttBae : BuffBase
local SpeedAttBae = class("SneakBuff", AttBase)

function SpeedAttBae:initialize(...)

end

return SpeedAttBae