---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by miao.
--- DateTime: 8/19/22 12:04 AM
---

local BuffBase = require "Battle.Buff.BuffBase"
--嘲讽
---@class TauntBuff : BuffBase
local TauntBuff = class("TauntBuff", BuffBase)

function TauntBuff:initialize(...)

    log("test taunt "  .. self.id)
end

return TauntBuff