---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by miaowenjie.
--- DateTime: 8/22/22 11:44 PM
---

---@class MessageManager
local MessageManager = class("MessageManager")

function MessageManager:initialize()
    self.messageStack = {}
end

function MessageManager:Push(msg)
    table.insert( self.messageStack , msg)
end

function MessageManager:Pop()
    local result = nil
    if #self.messageStack > 0 then
        result = table.remove(self.messageStack ,1 )
    end
    return result
end

function MessageManager:Top()
    return self.messageStack[1]
end

function MessageManager:Count()
    return #self.messageStack
end


return MessageManager